### ISSUE TITLE
wp_seo_get_bc_title is deprecated

### ISSUE THREAD

**Issue by flowdee** [wecobble/Subtitles#101]
https://github.com/wecobble/Subtitles/blob/992114173a98845bd4bc39e05e5226210cc93be7/public/class-subtitles.php#L245

Deprecated: wp_seo_get_bc_title
New: wpseo_breadcrumb_single_link_info

Would be great if you fix your plugin because it's throwing annoying PHP notices. Thanks ;)

**Comment by philiparthurmoore** [comment]
@flowdee So sorry for not getting on this. We unhooked Subtitles from Slack and I'm playing cleanup right now. Let me roll out a fix for this and push a new version of the plugin tomorrow!

**Comment by philiparthurmoore** [comment]
@flowdee Sorry for the late follow-up. Do you happen to have the specific PHP notice you're receiving and does it happen only when breadcrumbs in Yoast are turned on?

**Comment by flowdee** [comment]
Yes it only happens with enabled breadcrumbs.

`[01-Apr-2018 08:56:51 UTC] PHP Notice:  wp_seo_get_bc_title is <strong>deprecated</strong> since version WPSEO 5.8! Use wpseo_breadcrumb_single_link_info instead. in /wp-includes/functions.php on line 4090`

**Comment by philiparthurmoore** [comment]
@flowdee Perfect, thank you. Working on adjustments today and tomorrow. This is top of the list.

**Comment by flowdee** [comment]
Happy to hear 👍 

Right now I'm using a hook in all of my projects to prevent deprecated notices from showing up but of course this is only a temporary solution 😄

**Comment by philiparthurmoore** [comment]
Would you mind sharing your hook? I don't want to ruin your adjustments by pushing an errant update to the plugin.

**Comment by philiparthurmoore** [comment]
https://gist.github.com/robneu/7743769#gistcomment-2280213

**Comment by philiparthurmoore** [comment]
https://yoast.com/yoast-seo-5-8/

**Comment by philiparthurmoore** [comment]
<img width="626" alt="2018-04-07_20-31-11" src="https://user-images.githubusercontent.com/28684/38455465-a63ba62e-3aa2-11e8-8a77-6e102bdc3234.png">

https://wordpress.org/plugins/wordpress-seo/advanced/

**Comment by philiparthurmoore** [comment]
Working undocumented pseudocode. Will tidy this up tomorrow.

```php
add_filter( 'wpseo_breadcrumb_single_link_info', array( &$this, 'plugin_compat_wordpress_seo_new' ) );

public function plugin_compat_wordpress_seo_new( $breadcrumb_text ) {
	// check if in loop
	$in_the_loop = (bool) in_the_loop();
	if ( ! $in_the_loop ) {
		return $breadcrumb_text;
	}
	// subtitle
	$post_subtitle = get_the_subtitle(); // get subtitle
	$post_subtitle_length = (int) strlen( $post_subtitle ); // get subtitle length
	$post_subtitle_length_neg = -1 * $post_subtitle_length;
	// title
	$post_title = $breadcrumb_text['text']; // get post title
	$post_title_length = (int) strlen( $post_title ); // get post title length
	// remove subtitle from breadcrumb title
	if ( ( $post_title == $post_subtitle ) || ( '' == $post_title ) ) {
		return $breadcrumb_text;
	}
	$post_title = substr( $post_title, 0, $post_subtitle_length_neg );
	$post_title = apply_filters( 'compat_wordpress_seo', $post_title );
	$reconstructed_title = $post_title . $post_subtitle;
	if ( $reconstructed_title == $breadcrumb_text['text'] ) {
		$breadcrumb_text['text'] = $post_title;
		return $breadcrumb_text;
	}
	return $breadcrumb_text;
}
```

**Comment by philiparthurmoore** [comment]
Noting that this will require a plugin version bump to 4.0.0.
