### ISSUE TITLE
Astra theme and comment title

### ISSUE THREAD

**Issue by madz00** [wecobble/Subtitles#107]
Hi there,
there is some problem with astra theme and the plugin output in the comment area.
It seems there is something wrong in the html markup, please take a look at the screenshot.

<img width="815" alt="hello_world" src="https://user-images.githubusercontent.com/17091159/41131744-681555de-6abd-11e8-8317-6bd8d17de55f.png">

**Comment by philiparthurmoore** [comment]
Hi there. Have you seen [this](https://github.com/wecobble/Subtitles#theres-weird-html-showing-up-on-my-site)?
