### ISSUE TITLE
Not Showing Any More

### ISSUE THREAD

**Issue by RixBtrfly** [wecobble/Subtitles#110]
The Subtitles plugin appears to be functioning in the backend, but it is no longer showing on my website where people can see them. Help please! My website is tjstaste.com if that is helpful. Thank  you kindly!

**Comment by RixBtrfly** [comment]
Nope, I have not. Same theme it's been for past 2 years. It's Genesis with a child theme (child theme never changes, Genesis does update occasionally, but I didn't notice it being from an update).

**Comment by philiparthurmoore** [comment]
Thanks for the heads up. Genesis isn't free so it's a bit impossible to debug without theme files. You'd need to email us at support@wecobble.com for more assistance.
