### ISSUE TITLE
Can't see subtitle box in Gutenberg

### ISSUE THREAD

**Issue by iamstillalexh** [wecobble/Subtitles#111]
The subtitle box doesn't show up in the Gutenberg editor. I figured out how to edit with the classic editor and the subtitle box is still there, but like most things I'm sure they'll be phasing out the classic editor soon. Just wanted to give a heads up that this plugin is probably going to need to be updated for that.

**Comment by philiparthurmoore** [comment]
Thanks a ton. This is addressed in https://github.com/wecobble/Subtitles/issues/104
