### ISSUE TITLE
Title and subtitle are shown twice in category and tag view

### ISSUE THREAD

**Issue by thomaskoren** [wecobble/Subtitles#81]
In default posts overview, everything looks great. But when I click on a tag or category to display all posts within it, the title of each post is rendered like this:

Uncategorized 2016-06-13
This is a title
This is a subtitle
">This is a title
This is a subtitle
Her is the inital paragraph of the post

I am using hueman theme on WP 2.5.2 and subtitles 2.2.1

Thank you for your help!

**Comment by philiparthurmoore** [comment]
Hey Thomas. Is that a free or premium theme? What's the link to it?

**Comment by thomaskoren** [comment]
It is free and you can find it here: https://wordpress.org/themes/hueman/

**Comment by philiparthurmoore** [comment]
@thomaskoren, sorry for the delayed response. We've been absolutely swamped. I'm 100% sure this is a theme bug but I won't be able to dig into it until at some point this weekend. If you switch to a default theme and the issue goes away, then it's your theme. If you switch to a default theme and the issue persists, then it's a plugin bug. Let me know.

**Comment by philiparthurmoore** [comment]
@thomaskoren Did you ever get to the bottom of this?
