### ISSUE TITLE
Feature request: Kicker

### ISSUE THREAD

**Issue by TBarregren** [wecobble/Subtitles#84]
First of all, thank you for a great plugin.

This is a feature request for the possibility to also do kickers (see http://www.easymedia.in/kickers-newspapers-use-even-today/).

A simple but working solution would to have a drop down menu after the additional heading field. It's default value could be "Subheading", which gives exact the same behaviors as today. But there should  also be a "Kicker" alternative, which but the subheading above the title in the output.

**Comment by philiparthurmoore** [comment]
I have no idea what a kicker is but I'm keeping this open because you've
totally tickled my curiosity. Let me give this a read and a think and get
back to you as soon as I can. Thanks so much for the suggestion.

**Comment by philiparthurmoore** [comment]
@TBarregren This would actually make for an interesting addition. The subtitle would be _below_ the title and the kicker would be _above_, correct?

**Comment by philiparthurmoore** [comment]
Closing due to lack of reporter feedback. Feel free to open and discuss when ready. Thanks.

**Comment by philiparthurmoore** [comment]
Followed up here: https://github.com/wecobble/Subtitles/issues/97

**Comment by TBarregren** [comment]
Sorry I didn't answer in October. I was bogged down with work at the time and then forgot it. :-/ Anyway…

In news papers and some magazines there are three titles that can be combined:

Kicker: This a short heading above the main heading. It is used to give a context for the main heading, e.g. a topic, a reference to an ongoing event. It could also be used to explain a (too) clever heading. Here is an illustration: https://sv.wikipedia.org/wiki/Tidningsrubrik#/media/File:D%C3%A5rrad.png

Headline (a.k.a. hed): This is the main heading (title in WordPress parlance).

Deck (a.k.a. dek and standfirst): This is a subtitle. Its purpose is to clarify the heading and indicate the angle of the piece. It is often used for a quote from the text, which helps to specify the angle of the article. It can also be a direct continuation of the heading. Here is an illustration: https://sv.wikipedia.org/wiki/Tidningsrubrik#/media/File:Nedryckare.png

Kicker and deck are always used along with the main heading and never used at the same time. Thus, following combinations are valid:

1) Kicker followed by a headline
2) Headline only
3) Headline followed by a deck

A simple way to solve this could be selector next to the subtitle field. By default it says that the subtitle is a deck, but you can also choose to make it a kicker. The HTML could be the same, except that the kicker is placed before instead after the heading.
