### ISSUE TITLE
Subtitles on Portfolio

### ISSUE THREAD

**Issue by Onenn** [wecobble/Subtitles#95]
I have installed Subtitles on my website. I am trying to use it on Portfolio items. The field is showing of in the backend but not on the front. Can you help?
Thanks

**Comment by philiparthurmoore** [comment]
What sort of Portfolio items are you referring to? Have you read the FAQ
about subtitles only showing up inside the Loop automatically? What theme
are you using? Does the same behavior persist if you switch to a default
theme?

Thanks a ton.

Philip Arthur Moore
Founder and CEO, We Cobble
We build digital products for people.™
Email: philip@wecobble.com
Web: https://wecobble.com/
Phone: +1-888-410-3280
Fax: +1-844-774-0503

**Comment by Onenn** [comment]
Hi Philip, 

Thanks for getting back to me so fast. 

The theme I am using is "Designer" from Array https://arraythemes.com/themes/designer-wordpress-theme/ which is a paid theme. Portfolio works pretty much as a post but is under Portfolio (all projects, add new,  project types, project tags). It was installed automatically with the theme (not as a plugin)
If I use the subtitle on a normal post, its working perfectly. 
I am not sure what the "Loop" is... Can you let me know where it is located and I can have a go?

Kind regards,Onenn

**Comment by philiparthurmoore** [comment]
Hi Onnen,

Mike and crew at Array make excellent themes. Jetpack portfolio support is
already baked into the plugin but I don’t know how Mike has developed that
custom post type.

Can you please ask them:

1. What is the post type slug for Portfolio posts?
2. Is it contained in the Loop?

Feel free to link them here.

Philip Arthur Moore
Founder and CEO, We Cobble
We build digital products for people.™
Email: philip@wecobble.com
Web: https://wecobble.com/
Phone: +1-888-410-3280
Fax: +1-844-774-0503

**Comment by philiparthurmoore** [comment]
Closing due to lack of feedback. Please open when ready. Thanks!
