### ISSUE TITLE
multiple subtitles 

### ISSUE THREAD

**Issue by anonymiz** [wecobble/Subtitles#96]
how can i add multiple subtitles 
![4e097c1c7a9c5f9cfd285d62e24b2732](https://user-images.githubusercontent.com/22165537/31143856-09249de2-a87f-11e7-9110-8b0c8405f39f.png)

**Comment by philiparthurmoore** [comment]
Hi there. This plugin adds subtitles to WordPress post titles. It is not intended to be used as a plugin for adding closed captions into various media. Hope this helps clear up the confusion.
