### ISSUE TITLE
Changing Font Size

### ISSUE THREAD

**Issue by aemmanuele** [wecobble/Subtitles#99]
Hi there, with a recent update to Avada, I noticed that the Subtitle text is smaller than that of the body text.How do I increase size?
![screen shot 2018-01-30 at 1 30 26 pm](https://user-images.githubusercontent.com/35971565/35584048-c61db8d0-05c1-11e8-9324-bf5dbab6c597.png)

**Comment by philiparthurmoore** [comment]
@aemmanuele Did you figure this out? We have CSS classes that you can use to change your font sizing. Do you have a link to the page in question so we can help you with this? Thanks a ton.

**Comment by mkrdip** [comment]
Hi @aemmanuele,

You can use Custom CSS like this to control font and sizes. 

`span.entry-subtitle {
    font-family: "Times New Roman", Times, serif;
    font-size: 24px;
    font-weight: 800;
}`

Cheers.

**Comment by philiparthurmoore** [comment]
Thanks, @mkrdip. Closing this. @aemmanuele Please let us know if you need anything else.
